# tap test configuration
files: ./test/src/**/*.spec.ts
coverage: false  # Messes with in-page functions
reporter: list
timeout: 0  # Disable
ts: true
node-arg:
  - --pending-deprecation
  - --trace-deprecation
  - --trace-warnings
